impex.sliders.controllers:
    -
        controller: SliderShowController
        route: sliders:main
        url: /sliders/{event_id:\d+}/
    -
        controller: SliderCommand
        route: sliders:command
        url: /sliders/command/
    -
        controller: RefreshTab
        route: sliders:refresh
        url: /sliders/{event_id:\d+}/refresh/{name}/
impex.sliders.admin_controllers:
    -
        controller: SliderAdminController
        route: sliders:admin
        url: /sliders/admin/
