version: '3'

services:

  app:
    build: .
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    labels:
      - "traefik.backend=app"
      - "traefik.frontend.rule=PathPrefix:/"

  postgres:
    image: postgres:10.1
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dumps:/dumps

volumes:
  postgres-data:
