version: '3.3'

services:
  app:
    build: .
    image: registry.socek.org/turniejkosza-scores:$VERSION
    env_file: env
    volumes:
      - ./code:/code
    ports:
      - "${BACKEND_PORT:-8000}:8000"

  postgres:
    image: postgres:10.1
    env_file: env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dumps:/dumps

volumes:
  postgres-data:
