version: '3'

services:
  traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    env_file: .env
    labels:
      - "traefik.enable=false"
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
      - "${TRAEFIK_ADMIN_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: .
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    labels:
      - "traefik.backend=app"
      - "traefik.frontend.rule=PathPrefix:/"

  postgres:
    image: postgres:10.1
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dumps:/dumps

volumes:
  postgres-data:
