impex.teams.controllers:
    -
        controller: TeamListController
        route: teams:admin:list
        url: /admin/teams
    -
        controller: TeamCreateController
        route: teams:admin:create
        url: /admin/teams/create
    -
        controller: TeamEditController
        route: teams:admin:edit
        url: /teams/{team_id:\d+}/
