impex.events.admin_controllers:
    -
        controller: EventListController
        route: events:admin:list
        url: /admin/event
    -
        controller: EventCreateController
        route: events:admin:create
        url: /admin/event/create
    -
        controller: EventEditController
        route: events:admin:edit
        url: /event/{event_id:\d+}/
impex.events.controllers:
    -
        controller: EventListController
        route: events:list
        url: /
    -
        controller: EventListController
        route: home
        url: /
