impex.home.controller:
    -
        controller: HomeController
        route: home
        url: /
impex.auth.controllers:
    -
        controller: ImpexLoginController
        route: auth:login
        url: /login
    -
        controller: ImpexLogoutController
        route: auth:logout
        url: /logout
    -
        controller: ImpexRegisterController
        route: auth:register
        url: /register
