impex.games.admin_controllers:
    -
        controller: GameListController
        route: games:admin:list
        url: /event/{event_id:\d+}/games/
    -
        controller: GameCreateController
        route: games:admin:create
        url: /event/{event_id:\d+}/games/create/
